name: OptEco
version: @VERSION@
api-version: 1.13
description: "The powerful points system plugin of Minecraft Server"
main: me.playernguyen.opteco.OptEco
author: Player_Nguyen
loadbefore: [ BossShopPro, ShopGUIPlus ]
softdepend: [ PlaceholderAPI, BossShopPro, MVdWPlaceholderAPI, ShopGUIPlus ]
commands:
  opteco:
    usage: /opteco help
    description: Command of the OptEco plugin
    aliases: [ points, pts, p ]
  playerpointtoopteco:
    usage: /ppto
    description: To convert all data to the OptEco with one command
    aliases: [ppto, pptoopteco, pptoopt]
permissions:
  opteco.admin:
    description: Grant access to admin tool / command
    default: op
    children:
      opteco.take: true
      opteco.add: true
      opteco.check: true
      opteco.reload: true
      opteco.set: true
      opteco.me: true
      opteco.top: true
      opteco.confirm: true
      opteco.cancel: true
      opteco.pay: true
  opteco.user:
    description: Grant access to user command
    default: true
    children:
      opteco.me: true
      opteco.top: true
      opteco.confirm: true
      opteco.cancel: true
      opteco.pay: true
  opteco.take:
    description: Grant access to use /points take
    default: op
  opteco.add:
    description: Grant access to use /points add
    default: op
  opteco.check:
    description: Grant access to use /points check
    default: op
  opteco.me:
    description: Grant access to use /points me
    default: op
  opteco.pay:
    description: Grant access to use /points pay
    default: op
  opteco.reload:
    description: Grant access to use /points reload
    default: op
  opteco.set:
    description: Grant access to use /points set
    default: op
  opteco.confirm:
    description: Grant access to use /points confirm
    default: op
  opteco.cancel:
    description: Grant access to use /points cancel
    default: op
  opteco.top:
    description: Grant access to use /points top
    default: op